---
title: "Oretan"
subtitle: "Oret-oret"
author: "<large>Tedy Herlambang</large>"
# institute: "<small>Graduate Institute Geneva</small>" # uncomment to include
# date: "`r format(Sys.Date(), '%A, %e %B, %Y')`" # uncomment to include
output:
  xaringan::moon_reader:
    seal: false
    css: 
      - "default"
      - "assets/iheid-xaringan-style.css"
      - "https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
      - "ninjutsu"
    chakra: "https://remarkjs.com/downloads/remark-latest.min.js"
    # if you want to work offline, run the following command...
    # xaringan::summon_remark()
    # ...and then comment out lines 10-13 and uncomment lines 14-15:
    # lib_dir: libs
    # chakra: libs/remark-latest.min.js # For offline
    nature:
      ratio: '16:9'
      highlightStyle: github
      highlightLines: true
      beforeInit: "assets/macros.js"
      countIncrementalSlides: false
      slideNumberFormat: |
        <div class="progress-bar-container">
          <div class="progress-bar" style="width: calc(%current% / %total% * 100%);">
          </div>
        </div>`
---
1

```{r setup, include=FALSE}
# don't mind this code chunk, it just sets up a few things for the rest
# it doesn't appear, because the include argument above is FALSE...
options(htmltools.dir.version = FALSE, servr.daemon = TRUE)
knitr::opts_chunk$set(cache=TRUE, autodep = TRUE, fig.retina = 3, message = FALSE, warning = FALSE)
old <- ggplot2::theme_set(iheiddown::theme_iheid())
```

```{r, load_refs, include=FALSE, cache=FALSE}
# Initializes the bibliography
library(RefManageR)
BibOptions(check.entries = FALSE,
           bib.style = "authoryear", # Bibliography style
           max.names = 3, # Max author names displayed in bibliography
           sorting = "nyt", #Name, year, title sorting
           cite.style = "authoryear", # citation style
           style = "markdown",
           hyperlink = FALSE,
           dashed = FALSE)
myBib <- ReadBib("assets/myBib.bib", check = FALSE)
# Note: don't forget to clear the knitr cache to account for changes in the
# bibliography.
```

```{r xaringanExtra, echo=FALSE}
xaringanExtra::use_xaringan_extra(c("tile_view", "animate_css", "tachyons", "scribble"))
```

---
2

---
3

---
4

---
5

---
6

---
class: inverse, iheid-red
7


